// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/vibe-exploration/DarkCommand.tsx": () => import("../components/mockups/vibe-exploration/DarkCommand.tsx"),
  "./components/mockups/vibe-exploration/NoGeometry.tsx": () => import("../components/mockups/vibe-exploration/NoGeometry.tsx"),
  "./components/mockups/vibe-exploration/RawData.tsx": () => import("../components/mockups/vibe-exploration/RawData.tsx"),
  "./components/mockups/vibe-exploration/SoftFocus.tsx": () => import("../components/mockups/vibe-exploration/SoftFocus.tsx"),
  "./components/mockups/vibe-exploration/WarmCraft.tsx": () => import("../components/mockups/vibe-exploration/WarmCraft.tsx"),
  "./components/mockups/dashboard-inversions/CommandCenter.tsx": () => import("../components/mockups/dashboard-inversions/CommandCenter.tsx"),
  "./components/mockups/dashboard-inversions/LightAiry.tsx": () => import("../components/mockups/dashboard-inversions/LightAiry.tsx")
};
